name: baddel
description: The Tinder-Shopping App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
  flutter_image_compress: ^2.0.3
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#000000"
